export default {
  features: {
    theme: [
      'ADMINISTRATIVE',
      'DAMAGE_PREVENTION',
      'EMERGENCY_MANAGEMENT',
      'ENFORCEMENT',
      'ENVIRONMENTAL_PROTECTION',
      'FINANCIAL',
      'INTEGRITY_MANAGEMENT',
      'MANAGEMENT_SYSTEM',
      'SAFETY_MANAGEMENT',
      'SECURITY',
      'SOCIO_ECONOMIC',
      'STANDARD_CONDITION',
      'SUNSET_CLAUSE',
    ],
    phase: [
      'ABANDONMENT',
      'DURING_CONSTRUCTION_PHASE',
      'EXPIRY_DATE_OF_REGULATORY_INSTRUMENT',
      'INCLUDES_ALL_PHASES_OF_CONSTRUCTION',
      'NOT_CONSTRUCTION_RELATED',
      'POST_CONSTRUCTION_PHASE',
      'PRIOR_TO_CONSTRUCTION_PHASE',
      'UNSPECIFIED',
    ],
    status: [
      'AMENDED',
      'AWAITING_FILING',
      'AWAITING_IR_RESPONSE',
      'CLOSED',
      'FURTHER_INFORMATION_REQUIRED',
      'IN_PROGRESS',
      'NO_FILING_REQUIRED',
      'OVERDUE_FILING',
      'READY_FOR_BOARD_DECISION',
      'REVIEW_COMPLETE',
      'SATISFACTORY',
      'UNDER_REVIEW',
    ],
    type: [
      'STANDARD',
      'NON_STANDARD',
    ],
    filing: [
      'REQUIRED',
      'NOT_REQUIRED',
    ],
    instrument: [
      'CPTC',
      'GPL',
      'GPMO',
      'GPSO',
      'KAX',
      'MH',
      'MHW',
      'MO',
      'OH',
      'OPL',
      'OPLO',
      'OPSP',
      'TG',
      'XE',
      'XG',
      'ZO',
    ],
  },
};
