export default {
  id: null,
  name: {
    en: '',
    fr: '',
  },
  shortName: {
    en: '',
    fr: '',
  },
  data: {
    instrument: {
      ROUTING: 0,
      CONSTRUCTION: 0,
      ABANDONMENT: 0,
      OPENING: 0,
      MISC: 0,
      SAFETY: 0,
      TARIFFS: 0,
    },
    theme: {
      ADMINISTRATIVE: 0,
      DAMAGE_PREVENTION: 0,
      EMERGENCY_MANAGEMENT: 0,
      ENFORCEMENT: 0,
      ENVIRONMENTAL_PROTECTION: 0,
      FINANCIAL: 0,
      INTEGRITY_MANAGEMENT: 0,
      MANAGEMENT_SYSTEM: 0,
      SAFETY_MANAGEMENT: 0,
      SECURITY: 0,
      SOCIO_ECONOMIC: 0,
      STANDARD_CONDITION: 0,
      SUNSET_CLAUSE: 0,
    },
    phase: {
      ABANDONMENT: 0,
      DURING_CONSTRUCTION_PHASE: 0,
      EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 6,
      INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 0,
      NOT_CONSTRUCTION_RELATED: 33,
      POST_CONSTRUCTION_PHASE: 0,
      PRIOR_TO_CONSTRUCTION_PHASE: 0,
      UNSPECIFIED: 0,
    },
    status: {
      IN_PROGRESS: 0,
      CLOSED: 0,
      NO_FILING_REQUIRED: 0,
      AWAITING_FILING: 0,
      OVERDUE_FILING: 0,
      UNDER_REVIEW: 0,
      REVIEW_COMPLETE: 0,
      AWAITING_IR_RESPONSE: 0,
      READY_FOR_BOARD_DECISION: 0,
      FURTHER_INFORMATION_REQUIRED: 0,
      AMENDED: 0,
      SATISFACTORY: 0,
    },
    type: {
      NON_STANDARD: 0,
      STANDARD: 0,
    },
    filing: {
      REQUIRED: 0,
      NOT_REQUIRED: 0,
    },
  },
};
