const locationData = [
  {
    id: 1,
    name: {
      en: 'Prince Albert',
      __typename: 'TranslatedStringType',
    },
    province: 'SK',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 4,
        DAMAGE_PREVENTION: 2,
        EMERGENCY_MANAGEMENT: 2,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 7,
        FINANCIAL: 6,
        INTEGRITY_MANAGEMENT: 8,
        MANAGEMENT_SYSTEM: 2,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 1,
        STANDARD_CONDITION: 20,
        SUNSET_CLAUSE: 5,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 41,
        IN_PROGRESS: 9,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 30,
        STANDARD: 20,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 20,
        REQUIRED: 30,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 10,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 4,
        INCLUDES_ALL_PHASES_OF_CONSTR: 10,
        NOT_CONSTRUCTION_RELATED: 23,
        POST_CONSTRUCTION_PHASE: 3,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 2,
    name: {
      en: 'Camrose--Drumheller',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 78,
        DAMAGE_PREVENTION: 5,
        EMERGENCY_MANAGEMENT: 14,
        ENFORCEMENT: 145,
        ENVIRONMENTAL_PROTECTION: 162,
        FINANCIAL: 43,
        INTEGRITY_MANAGEMENT: 259,
        MANAGEMENT_SYSTEM: 14,
        SAFETY_MANAGEMENT: 19,
        SECURITY: 9,
        SOCIO_ECONOMIC: 65,
        STANDARD_CONDITION: 291,
        SUNSET_CLAUSE: 62,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 702,
        IN_PROGRESS: 162,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 571,
        STANDARD: 293,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 439,
        REQUIRED: 425,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 74,
        DURING_CONSTRUCTION_PHASE: 40,
        EXPIRY_DATE_OF_REG_INSTR: 57,
        INCLUDES_ALL_PHASES_OF_CONSTR: 201,
        NOT_CONSTRUCTION_RELATED: 258,
        POST_CONSTRUCTION_PHASE: 118,
        PRIOR_TO_CONSTRUCTION_PHASE: 70,
        UNSPECIFIED: 46,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 3,
    name: {
      en: 'Northwest',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 4,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 13,
        ENVIRONMENTAL_PROTECTION: 4,
        FINANCIAL: 6,
        INTEGRITY_MANAGEMENT: 14,
        MANAGEMENT_SYSTEM: 5,
        SAFETY_MANAGEMENT: 2,
        SECURITY: 0,
        SOCIO_ECONOMIC: 1,
        STANDARD_CONDITION: 13,
        SUNSET_CLAUSE: 3,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 43,
        IN_PROGRESS: 2,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 32,
        STANDARD: 13,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 20,
        REQUIRED: 25,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 3,
        INCLUDES_ALL_PHASES_OF_CONSTR: 9,
        NOT_CONSTRUCTION_RELATED: 27,
        POST_CONSTRUCTION_PHASE: 4,
        PRIOR_TO_CONSTRUCTION_PHASE: 2,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 4,
    name: {
      en: 'Lethbridge--Medicine Hat',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 29,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 9,
        ENFORCEMENT: 35,
        ENVIRONMENTAL_PROTECTION: 90,
        FINANCIAL: 31,
        INTEGRITY_MANAGEMENT: 101,
        MANAGEMENT_SYSTEM: 7,
        SAFETY_MANAGEMENT: 12,
        SECURITY: 2,
        SOCIO_ECONOMIC: 27,
        STANDARD_CONDITION: 114,
        SUNSET_CLAUSE: 22,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 334,
        IN_PROGRESS: 60,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 280,
        STANDARD: 114,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 159,
        REQUIRED: 235,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 48,
        DURING_CONSTRUCTION_PHASE: 20,
        EXPIRY_DATE_OF_REG_INSTR: 21,
        INCLUDES_ALL_PHASES_OF_CONSTR: 69,
        NOT_CONSTRUCTION_RELATED: 85,
        POST_CONSTRUCTION_PHASE: 57,
        PRIOR_TO_CONSTRUCTION_PHASE: 68,
        UNSPECIFIED: 26,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 5,
    name: {
      en: 'Cape Breton',
      __typename: 'TranslatedStringType',
    },
    province: 'NS',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 3,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 9,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 15,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 15,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 0,
        REQUIRED: 15,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 5,
        POST_CONSTRUCTION_PHASE: 10,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 6,
    name: {
      en: 'Montréal',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 8,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 5,
        ENFORCEMENT: 27,
        ENVIRONMENTAL_PROTECTION: 5,
        FINANCIAL: 5,
        INTEGRITY_MANAGEMENT: 53,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 2,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 16,
        SUNSET_CLAUSE: 3,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 74,
        IN_PROGRESS: 17,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 75,
        STANDARD: 16,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 31,
        REQUIRED: 60,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 3,
        INCLUDES_ALL_PHASES_OF_CONSTR: 12,
        NOT_CONSTRUCTION_RELATED: 61,
        POST_CONSTRUCTION_PHASE: 6,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 9,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 7,
    name: {
      en: 'London',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 6,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 2,
        ENFORCEMENT: 15,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 0,
        INTEGRITY_MANAGEMENT: 8,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 2,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 4,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 24,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 20,
        STANDARD: 4,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 5,
        REQUIRED: 19,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 14,
        POST_CONSTRUCTION_PHASE: 3,
        PRIOR_TO_CONSTRUCTION_PHASE: 2,
        UNSPECIFIED: 1,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 8,
    name: {
      en: 'Outaouais',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 0,
        FINANCIAL: 4,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 2,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 13,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 22,
        IN_PROGRESS: 1,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 9,
        STANDARD: 14,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 5,
        REQUIRED: 18,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 8,
        POST_CONSTRUCTION_PHASE: 0,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 13,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 9,
    name: {
      en: 'Moncton--Richibucto',
      __typename: 'TranslatedStringType',
    },
    province: 'NB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 3,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 3,
        MANAGEMENT_SYSTEM: 9,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 4,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 21,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 17,
        STANDARD: 4,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 4,
        REQUIRED: 17,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 2,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 11,
        PRIOR_TO_CONSTRUCTION_PHASE: 1,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 11,
    name: {
      en: 'Halifax',
      __typename: 'TranslatedStringType',
    },
    province: 'NS',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 9,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 13,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 13,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 0,
        REQUIRED: 13,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 10,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 12,
    name: {
      en: 'South Central',
      __typename: 'TranslatedStringType',
    },
    province: 'MB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 30,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 6,
        ENFORCEMENT: 25,
        ENVIRONMENTAL_PROTECTION: 45,
        FINANCIAL: 4,
        INTEGRITY_MANAGEMENT: 47,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 5,
        SECURITY: 5,
        SOCIO_ECONOMIC: 39,
        STANDARD_CONDITION: 54,
        SUNSET_CLAUSE: 13,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 151,
        IN_PROGRESS: 63,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 160,
        STANDARD: 54,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 79,
        REQUIRED: 135,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 29,
        EXPIRY_DATE_OF_REG_INSTR: 13,
        INCLUDES_ALL_PHASES_OF_CONSTR: 42,
        NOT_CONSTRUCTION_RELATED: 33,
        POST_CONSTRUCTION_PHASE: 42,
        PRIOR_TO_CONSTRUCTION_PHASE: 37,
        UNSPECIFIED: 18,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 13,
    name: {
      en: 'Abitibi-Témiscamingue',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 2,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 1,
        SECURITY: 1,
        SOCIO_ECONOMIC: 1,
        STANDARD_CONDITION: 8,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 17,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 9,
        STANDARD: 8,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 8,
        REQUIRED: 9,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 6,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 2,
        PRIOR_TO_CONSTRUCTION_PHASE: 4,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 14,
    name: {
      en: 'Banff--Jasper--Rocky Mountain House',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 53,
        DAMAGE_PREVENTION: 2,
        EMERGENCY_MANAGEMENT: 41,
        ENFORCEMENT: 29,
        ENVIRONMENTAL_PROTECTION: 267,
        FINANCIAL: 16,
        INTEGRITY_MANAGEMENT: 197,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 9,
        SECURITY: 8,
        SOCIO_ECONOMIC: 100,
        STANDARD_CONDITION: 198,
        SUNSET_CLAUSE: 42,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 478,
        IN_PROGRESS: 350,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 623,
        STANDARD: 205,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 236,
        REQUIRED: 592,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 3,
        DURING_CONSTRUCTION_PHASE: 90,
        EXPIRY_DATE_OF_REG_INSTR: 46,
        INCLUDES_ALL_PHASES_OF_CONSTR: 215,
        NOT_CONSTRUCTION_RELATED: 53,
        POST_CONSTRUCTION_PHASE: 142,
        PRIOR_TO_CONSTRUCTION_PHASE: 261,
        UNSPECIFIED: 18,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 15,
    name: {
      en: 'Laval',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 3,
        ENFORCEMENT: 11,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 3,
        INTEGRITY_MANAGEMENT: 43,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 34,
        IN_PROGRESS: 17,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 51,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 15,
        REQUIRED: 36,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 43,
        POST_CONSTRUCTION_PHASE: 0,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 8,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 16,
    name: {
      en: 'North Central',
      __typename: 'TranslatedStringType',
    },
    province: 'MB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 7,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 7,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 8,
        INTEGRITY_MANAGEMENT: 4,
        MANAGEMENT_SYSTEM: 6,
        SAFETY_MANAGEMENT: 1,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 10,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 30,
        IN_PROGRESS: 3,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 23,
        STANDARD: 10,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 7,
        REQUIRED: 26,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 23,
        POST_CONSTRUCTION_PHASE: 1,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 5,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 17,
    name: {
      en: 'Muskoka--Kawarthas',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 12,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 7,
        ENFORCEMENT: 16,
        ENVIRONMENTAL_PROTECTION: 5,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 17,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 2,
        SECURITY: 0,
        SOCIO_ECONOMIC: 3,
        STANDARD_CONDITION: 4,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 45,
        IN_PROGRESS: 6,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 47,
        STANDARD: 4,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 6,
        REQUIRED: 45,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 5,
        NOT_CONSTRUCTION_RELATED: 18,
        POST_CONSTRUCTION_PHASE: 23,
        PRIOR_TO_CONSTRUCTION_PHASE: 3,
        UNSPECIFIED: 1,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 18,
    name: {
      en: 'Regina--Moose Mountain',
      __typename: 'TranslatedStringType',
    },
    province: 'SK',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 65,
        DAMAGE_PREVENTION: 45,
        EMERGENCY_MANAGEMENT: 58,
        ENFORCEMENT: 53,
        ENVIRONMENTAL_PROTECTION: 129,
        FINANCIAL: 35,
        INTEGRITY_MANAGEMENT: 239,
        MANAGEMENT_SYSTEM: 12,
        SAFETY_MANAGEMENT: 21,
        SECURITY: 9,
        SOCIO_ECONOMIC: 55,
        STANDARD_CONDITION: 308,
        SUNSET_CLAUSE: 49,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 787,
        IN_PROGRESS: 115,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 594,
        STANDARD: 308,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 318,
        REQUIRED: 584,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 60,
        EXPIRY_DATE_OF_REG_INSTR: 55,
        INCLUDES_ALL_PHASES_OF_CONSTR: 168,
        NOT_CONSTRUCTION_RELATED: 366,
        POST_CONSTRUCTION_PHASE: 120,
        PRIOR_TO_CONSTRUCTION_PHASE: 109,
        UNSPECIFIED: 24,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 19,
    name: {
      en: 'Capitale-Nationale',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 5,
        ENVIRONMENTAL_PROTECTION: 0,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 17,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 18,
        IN_PROGRESS: 3,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 21,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 2,
        REQUIRED: 19,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 1,
        NOT_CONSTRUCTION_RELATED: 6,
        POST_CONSTRUCTION_PHASE: 3,
        PRIOR_TO_CONSTRUCTION_PHASE: 1,
        UNSPECIFIED: 9,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 20,
    name: {
      en: 'Calgary',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 27,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 113,
        ENVIRONMENTAL_PROTECTION: 12,
        FINANCIAL: 5,
        INTEGRITY_MANAGEMENT: 140,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 6,
        SECURITY: 1,
        SOCIO_ECONOMIC: 4,
        STANDARD_CONDITION: 39,
        SUNSET_CLAUSE: 5,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 195,
        IN_PROGRESS: 30,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 186,
        STANDARD: 39,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 160,
        REQUIRED: 65,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 7,
        EXPIRY_DATE_OF_REG_INSTR: 6,
        INCLUDES_ALL_PHASES_OF_CONSTR: 27,
        NOT_CONSTRUCTION_RELATED: 136,
        POST_CONSTRUCTION_PHASE: 12,
        PRIOR_TO_CONSTRUCTION_PHASE: 8,
        UNSPECIFIED: 29,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 21,
    name: {
      en: 'Saskatoon--Biggar',
      __typename: 'TranslatedStringType',
    },
    province: 'SK',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 20,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 4,
        ENFORCEMENT: 37,
        ENVIRONMENTAL_PROTECTION: 44,
        FINANCIAL: 13,
        INTEGRITY_MANAGEMENT: 55,
        MANAGEMENT_SYSTEM: 7,
        SAFETY_MANAGEMENT: 5,
        SECURITY: 2,
        SOCIO_ECONOMIC: 12,
        STANDARD_CONDITION: 86,
        SUNSET_CLAUSE: 20,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 190,
        IN_PROGRESS: 31,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 134,
        STANDARD: 87,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 96,
        REQUIRED: 125,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 16,
        DURING_CONSTRUCTION_PHASE: 13,
        EXPIRY_DATE_OF_REG_INSTR: 19,
        INCLUDES_ALL_PHASES_OF_CONSTR: 58,
        NOT_CONSTRUCTION_RELATED: 57,
        POST_CONSTRUCTION_PHASE: 40,
        PRIOR_TO_CONSTRUCTION_PHASE: 16,
        UNSPECIFIED: 2,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 22,
    name: {
      en: 'Mauricie',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 5,
        ENVIRONMENTAL_PROTECTION: 0,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 17,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 18,
        IN_PROGRESS: 3,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 21,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 2,
        REQUIRED: 19,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 1,
        NOT_CONSTRUCTION_RELATED: 6,
        POST_CONSTRUCTION_PHASE: 3,
        PRIOR_TO_CONSTRUCTION_PHASE: 1,
        UNSPECIFIED: 9,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 23,
    name: {
      en: 'Southeast',
      __typename: 'TranslatedStringType',
    },
    province: 'MB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 4,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 1,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 4,
        INTEGRITY_MANAGEMENT: 4,
        MANAGEMENT_SYSTEM: 5,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 9,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 25,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 16,
        STANDARD: 9,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 10,
        REQUIRED: 15,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 6,
        NOT_CONSTRUCTION_RELATED: 13,
        POST_CONSTRUCTION_PHASE: 4,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 24,
    name: {
      en: 'Estrie',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 3,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 4,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 12,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 16,
        SUNSET_CLAUSE: 4,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 26,
        IN_PROGRESS: 7,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 15,
        STANDARD: 18,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 16,
        REQUIRED: 17,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 4,
        INCLUDES_ALL_PHASES_OF_CONSTR: 12,
        NOT_CONSTRUCTION_RELATED: 4,
        POST_CONSTRUCTION_PHASE: 9,
        PRIOR_TO_CONSTRUCTION_PHASE: 4,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 25,
    name: {
      en: 'Toronto',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 21,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 12,
        ENFORCEMENT: 27,
        ENVIRONMENTAL_PROTECTION: 41,
        FINANCIAL: 8,
        INTEGRITY_MANAGEMENT: 103,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 6,
        SECURITY: 0,
        SOCIO_ECONOMIC: 23,
        STANDARD_CONDITION: 64,
        SUNSET_CLAUSE: 15,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 229,
        IN_PROGRESS: 37,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 200,
        STANDARD: 66,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 94,
        REQUIRED: 172,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 12,
        EXPIRY_DATE_OF_REG_INSTR: 15,
        INCLUDES_ALL_PHASES_OF_CONSTR: 53,
        NOT_CONSTRUCTION_RELATED: 73,
        POST_CONSTRUCTION_PHASE: 63,
        PRIOR_TO_CONSTRUCTION_PHASE: 37,
        UNSPECIFIED: 13,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 26,
    name: {
      en: 'Northwest Territories',
      __typename: 'TranslatedStringType',
    },
    province: 'NT',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 22,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 4,
        ENFORCEMENT: 12,
        ENVIRONMENTAL_PROTECTION: 45,
        FINANCIAL: 27,
        INTEGRITY_MANAGEMENT: 56,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 7,
        SECURITY: 0,
        SOCIO_ECONOMIC: 13,
        STANDARD_CONDITION: 23,
        SUNSET_CLAUSE: 4,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 74,
        IN_PROGRESS: 94,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 145,
        STANDARD: 23,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 51,
        REQUIRED: 117,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 17,
        EXPIRY_DATE_OF_REG_INSTR: 4,
        INCLUDES_ALL_PHASES_OF_CONSTR: 26,
        NOT_CONSTRUCTION_RELATED: 33,
        POST_CONSTRUCTION_PHASE: 21,
        PRIOR_TO_CONSTRUCTION_PHASE: 57,
        UNSPECIFIED: 10,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 27,
    name: {
      en: 'Fredericton--Oromocto',
      __typename: 'TranslatedStringType',
    },
    province: 'NB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 9,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 2,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 16,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 14,
        STANDARD: 2,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 2,
        REQUIRED: 14,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 2,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 10,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 28,
    name: {
      en: 'Lanaudière',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 14,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 7,
        ENFORCEMENT: 20,
        ENVIRONMENTAL_PROTECTION: 7,
        FINANCIAL: 4,
        INTEGRITY_MANAGEMENT: 47,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 3,
        SECURITY: 0,
        SOCIO_ECONOMIC: 3,
        STANDARD_CONDITION: 12,
        SUNSET_CLAUSE: 3,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 85,
        IN_PROGRESS: 11,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 84,
        STANDARD: 12,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 28,
        REQUIRED: 68,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 3,
        INCLUDES_ALL_PHASES_OF_CONSTR: 12,
        NOT_CONSTRUCTION_RELATED: 30,
        POST_CONSTRUCTION_PHASE: 33,
        PRIOR_TO_CONSTRUCTION_PHASE: 4,
        UNSPECIFIED: 13,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 29,
    name: {
      en: 'Swift Current--Moose Jaw',
      __typename: 'TranslatedStringType',
    },
    province: 'SK',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 23,
        DAMAGE_PREVENTION: 1,
        EMERGENCY_MANAGEMENT: 11,
        ENFORCEMENT: 19,
        ENVIRONMENTAL_PROTECTION: 60,
        FINANCIAL: 14,
        INTEGRITY_MANAGEMENT: 65,
        MANAGEMENT_SYSTEM: 7,
        SAFETY_MANAGEMENT: 6,
        SECURITY: 1,
        SOCIO_ECONOMIC: 24,
        STANDARD_CONDITION: 77,
        SUNSET_CLAUSE: 15,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 226,
        IN_PROGRESS: 42,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 189,
        STANDARD: 79,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 95,
        REQUIRED: 173,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 10,
        DURING_CONSTRUCTION_PHASE: 18,
        EXPIRY_DATE_OF_REG_INSTR: 17,
        INCLUDES_ALL_PHASES_OF_CONSTR: 59,
        NOT_CONSTRUCTION_RELATED: 44,
        POST_CONSTRUCTION_PHASE: 47,
        PRIOR_TO_CONSTRUCTION_PHASE: 60,
        UNSPECIFIED: 13,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 30,
    name: {
      en: 'Red Deer',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 24,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 3,
        INTEGRITY_MANAGEMENT: 37,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 5,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 38,
        IN_PROGRESS: 9,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 42,
        STANDARD: 5,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 29,
        REQUIRED: 18,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 28,
        POST_CONSTRUCTION_PHASE: 1,
        PRIOR_TO_CONSTRUCTION_PHASE: 1,
        UNSPECIFIED: 12,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 31,
    name: {
      en: 'Nechako',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 0,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 3,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 3,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 0,
        REQUIRED: 3,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 0,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 32,
    name: {
      en: 'Edmonton',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 25,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 11,
        ENFORCEMENT: 36,
        ENVIRONMENTAL_PROTECTION: 69,
        FINANCIAL: 17,
        INTEGRITY_MANAGEMENT: 89,
        MANAGEMENT_SYSTEM: 7,
        SAFETY_MANAGEMENT: 9,
        SECURITY: 3,
        SOCIO_ECONOMIC: 17,
        STANDARD_CONDITION: 221,
        SUNSET_CLAUSE: 59,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 374,
        IN_PROGRESS: 42,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 192,
        STANDARD: 224,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 250,
        REQUIRED: 166,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 10,
        EXPIRY_DATE_OF_REG_INSTR: 58,
        INCLUDES_ALL_PHASES_OF_CONSTR: 176,
        NOT_CONSTRUCTION_RELATED: 55,
        POST_CONSTRUCTION_PHASE: 83,
        PRIOR_TO_CONSTRUCTION_PHASE: 15,
        UNSPECIFIED: 19,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 33,
    name: {
      en: 'Saint John--St. Stephen',
      __typename: 'TranslatedStringType',
    },
    province: 'NB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 2,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 0,
        MANAGEMENT_SYSTEM: 13,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 0,
        SUNSET_CLAUSE: 0,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 17,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 17,
        STANDARD: 0,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 3,
        REQUIRED: 14,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 0,
        INCLUDES_ALL_PHASES_OF_CONSTR: 0,
        NOT_CONSTRUCTION_RELATED: 7,
        POST_CONSTRUCTION_PHASE: 10,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 34,
    name: {
      en: 'Hamilton--Niagara Peninsula',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 27,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 13,
        ENFORCEMENT: 27,
        ENVIRONMENTAL_PROTECTION: 31,
        FINANCIAL: 9,
        INTEGRITY_MANAGEMENT: 115,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 5,
        SECURITY: 0,
        SOCIO_ECONOMIC: 14,
        STANDARD_CONDITION: 51,
        SUNSET_CLAUSE: 15,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 209,
        IN_PROGRESS: 46,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 202,
        STANDARD: 53,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 87,
        REQUIRED: 168,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 7,
        DURING_CONSTRUCTION_PHASE: 12,
        EXPIRY_DATE_OF_REG_INSTR: 15,
        INCLUDES_ALL_PHASES_OF_CONSTR: 46,
        NOT_CONSTRUCTION_RELATED: 72,
        POST_CONSTRUCTION_PHASE: 60,
        PRIOR_TO_CONSTRUCTION_PHASE: 30,
        UNSPECIFIED: 13,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 35,
    name: {
      en: 'Yorkton--Melville',
      __typename: 'TranslatedStringType',
    },
    province: 'SK',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 15,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 2,
        ENFORCEMENT: 22,
        ENVIRONMENTAL_PROTECTION: 16,
        FINANCIAL: 6,
        INTEGRITY_MANAGEMENT: 18,
        MANAGEMENT_SYSTEM: 10,
        SAFETY_MANAGEMENT: 4,
        SECURITY: 0,
        SOCIO_ECONOMIC: 1,
        STANDARD_CONDITION: 34,
        SUNSET_CLAUSE: 9,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 90,
        IN_PROGRESS: 3,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 59,
        STANDARD: 34,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 38,
        REQUIRED: 55,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 3,
        EXPIRY_DATE_OF_REG_INSTR: 9,
        INCLUDES_ALL_PHASES_OF_CONSTR: 24,
        NOT_CONSTRUCTION_RELATED: 34,
        POST_CONSTRUCTION_PHASE: 14,
        PRIOR_TO_CONSTRUCTION_PHASE: 7,
        UNSPECIFIED: 2,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 36,
    name: {
      en: 'Windsor--Sarnia',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 23,
        DAMAGE_PREVENTION: 2,
        EMERGENCY_MANAGEMENT: 10,
        ENFORCEMENT: 21,
        ENVIRONMENTAL_PROTECTION: 31,
        FINANCIAL: 23,
        INTEGRITY_MANAGEMENT: 66,
        MANAGEMENT_SYSTEM: 7,
        SAFETY_MANAGEMENT: 5,
        SECURITY: 0,
        SOCIO_ECONOMIC: 7,
        STANDARD_CONDITION: 101,
        SUNSET_CLAUSE: 20,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 237,
        IN_PROGRESS: 17,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 149,
        STANDARD: 105,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 110,
        REQUIRED: 144,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 8,
        EXPIRY_DATE_OF_REG_INSTR: 20,
        INCLUDES_ALL_PHASES_OF_CONSTR: 76,
        NOT_CONSTRUCTION_RELATED: 72,
        POST_CONSTRUCTION_PHASE: 51,
        PRIOR_TO_CONSTRUCTION_PHASE: 16,
        UNSPECIFIED: 11,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 37,
    name: {
      en: 'Athabasca--Grande Prairie--Peace River',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 74,
        DAMAGE_PREVENTION: 8,
        EMERGENCY_MANAGEMENT: 24,
        ENFORCEMENT: 51,
        ENVIRONMENTAL_PROTECTION: 343,
        FINANCIAL: 48,
        INTEGRITY_MANAGEMENT: 327,
        MANAGEMENT_SYSTEM: 6,
        SAFETY_MANAGEMENT: 23,
        SECURITY: 4,
        SOCIO_ECONOMIC: 98,
        STANDARD_CONDITION: 619,
        SUNSET_CLAUSE: 114,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 1210,
        IN_PROGRESS: 213,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 772,
        STANDARD: 651,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 637,
        REQUIRED: 786,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 65,
        DURING_CONSTRUCTION_PHASE: 100,
        EXPIRY_DATE_OF_REG_INSTR: 121,
        INCLUDES_ALL_PHASES_OF_CONSTR: 390,
        NOT_CONSTRUCTION_RELATED: 229,
        POST_CONSTRUCTION_PHASE: 261,
        PRIOR_TO_CONSTRUCTION_PHASE: 219,
        UNSPECIFIED: 38,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 38,
    name: {
      en: 'Ottawa',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 15,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 11,
        ENFORCEMENT: 27,
        ENVIRONMENTAL_PROTECTION: 16,
        FINANCIAL: 16,
        INTEGRITY_MANAGEMENT: 63,
        MANAGEMENT_SYSTEM: 6,
        SAFETY_MANAGEMENT: 4,
        SECURITY: 0,
        SOCIO_ECONOMIC: 10,
        STANDARD_CONDITION: 38,
        SUNSET_CLAUSE: 8,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 143,
        IN_PROGRESS: 27,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 132,
        STANDARD: 38,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 50,
        REQUIRED: 120,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 8,
        INCLUDES_ALL_PHASES_OF_CONSTR: 20,
        NOT_CONSTRUCTION_RELATED: 71,
        POST_CONSTRUCTION_PHASE: 35,
        PRIOR_TO_CONSTRUCTION_PHASE: 13,
        UNSPECIFIED: 22,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 39,
    name: {
      en: 'Kingston--Pembroke',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 13,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 10,
        ENFORCEMENT: 25,
        ENVIRONMENTAL_PROTECTION: 7,
        FINANCIAL: 7,
        INTEGRITY_MANAGEMENT: 72,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 3,
        SECURITY: 0,
        SOCIO_ECONOMIC: 3,
        STANDARD_CONDITION: 8,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 98,
        IN_PROGRESS: 25,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 115,
        STANDARD: 8,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 37,
        REQUIRED: 86,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 8,
        NOT_CONSTRUCTION_RELATED: 71,
        POST_CONSTRUCTION_PHASE: 27,
        PRIOR_TO_CONSTRUCTION_PHASE: 3,
        UNSPECIFIED: 12,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 40,
    name: {
      en: 'Montérégie',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 4,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 3,
        ENFORCEMENT: 12,
        ENVIRONMENTAL_PROTECTION: 6,
        FINANCIAL: 7,
        INTEGRITY_MANAGEMENT: 44,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 1,
        STANDARD_CONDITION: 20,
        SUNSET_CLAUSE: 5,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 65,
        IN_PROGRESS: 15,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 59,
        STANDARD: 21,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 34,
        REQUIRED: 46,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 5,
        INCLUDES_ALL_PHASES_OF_CONSTR: 15,
        NOT_CONSTRUCTION_RELATED: 46,
        POST_CONSTRUCTION_PHASE: 5,
        PRIOR_TO_CONSTRUCTION_PHASE: 1,
        UNSPECIFIED: 8,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 41,
    name: {
      en: 'Northeast',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 76,
        DAMAGE_PREVENTION: 5,
        EMERGENCY_MANAGEMENT: 28,
        ENFORCEMENT: 7,
        ENVIRONMENTAL_PROTECTION: 284,
        FINANCIAL: 50,
        INTEGRITY_MANAGEMENT: 198,
        MANAGEMENT_SYSTEM: 3,
        SAFETY_MANAGEMENT: 29,
        SECURITY: 6,
        SOCIO_ECONOMIC: 84,
        STANDARD_CONDITION: 488,
        SUNSET_CLAUSE: 83,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 965,
        IN_PROGRESS: 173,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 636,
        STANDARD: 502,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 460,
        REQUIRED: 678,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 34,
        DURING_CONSTRUCTION_PHASE: 99,
        EXPIRY_DATE_OF_REG_INSTR: 80,
        INCLUDES_ALL_PHASES_OF_CONSTR: 343,
        NOT_CONSTRUCTION_RELATED: 175,
        POST_CONSTRUCTION_PHASE: 213,
        PRIOR_TO_CONSTRUCTION_PHASE: 175,
        UNSPECIFIED: 19,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 42,
    name: {
      en: 'Wood Buffalo--Cold Lake',
      __typename: 'TranslatedStringType',
    },
    province: 'AB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 15,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 2,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 88,
        FINANCIAL: 4,
        INTEGRITY_MANAGEMENT: 49,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 7,
        SECURITY: 0,
        SOCIO_ECONOMIC: 26,
        STANDARD_CONDITION: 120,
        SUNSET_CLAUSE: 30,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 235,
        IN_PROGRESS: 44,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 159,
        STANDARD: 120,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 126,
        REQUIRED: 153,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 23,
        DURING_CONSTRUCTION_PHASE: 26,
        EXPIRY_DATE_OF_REG_INSTR: 29,
        INCLUDES_ALL_PHASES_OF_CONSTR: 90,
        NOT_CONSTRUCTION_RELATED: 5,
        POST_CONSTRUCTION_PHASE: 58,
        PRIOR_TO_CONSTRUCTION_PHASE: 45,
        UNSPECIFIED: 3,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 43,
    name: {
      en: 'Southwest',
      __typename: 'TranslatedStringType',
    },
    province: 'MB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 28,
        DAMAGE_PREVENTION: 6,
        EMERGENCY_MANAGEMENT: 8,
        ENFORCEMENT: 32,
        ENVIRONMENTAL_PROTECTION: 40,
        FINANCIAL: 12,
        INTEGRITY_MANAGEMENT: 59,
        MANAGEMENT_SYSTEM: 10,
        SAFETY_MANAGEMENT: 4,
        SECURITY: 0,
        SOCIO_ECONOMIC: 14,
        STANDARD_CONDITION: 113,
        SUNSET_CLAUSE: 24,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 250,
        IN_PROGRESS: 15,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 150,
        STANDARD: 115,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 129,
        REQUIRED: 136,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 6,
        EXPIRY_DATE_OF_REG_INSTR: 24,
        INCLUDES_ALL_PHASES_OF_CONSTR: 77,
        NOT_CONSTRUCTION_RELATED: 89,
        POST_CONSTRUCTION_PHASE: 36,
        PRIOR_TO_CONSTRUCTION_PHASE: 14,
        UNSPECIFIED: 19,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 44,
    name: {
      en: 'Laurentides',
      __typename: 'TranslatedStringType',
    },
    province: 'QC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 14,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 10,
        ENFORCEMENT: 29,
        ENVIRONMENTAL_PROTECTION: 8,
        FINANCIAL: 7,
        INTEGRITY_MANAGEMENT: 85,
        MANAGEMENT_SYSTEM: 4,
        SAFETY_MANAGEMENT: 3,
        SECURITY: 0,
        SOCIO_ECONOMIC: 3,
        STANDARD_CONDITION: 12,
        SUNSET_CLAUSE: 3,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 109,
        IN_PROGRESS: 32,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 128,
        STANDARD: 13,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 42,
        REQUIRED: 99,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 2,
        EXPIRY_DATE_OF_REG_INSTR: 6,
        INCLUDES_ALL_PHASES_OF_CONSTR: 9,
        NOT_CONSTRUCTION_RELATED: 68,
        POST_CONSTRUCTION_PHASE: 31,
        PRIOR_TO_CONSTRUCTION_PHASE: 4,
        UNSPECIFIED: 21,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 45,
    name: {
      en: 'Cariboo',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 41,
        DAMAGE_PREVENTION: 2,
        EMERGENCY_MANAGEMENT: 39,
        ENFORCEMENT: 5,
        ENVIRONMENTAL_PROTECTION: 204,
        FINANCIAL: 11,
        INTEGRITY_MANAGEMENT: 112,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 9,
        SECURITY: 7,
        SOCIO_ECONOMIC: 74,
        STANDARD_CONDITION: 64,
        SUNSET_CLAUSE: 14,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 244,
        IN_PROGRESS: 294,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 475,
        STANDARD: 63,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 78,
        REQUIRED: 460,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 76,
        EXPIRY_DATE_OF_REG_INSTR: 14,
        INCLUDES_ALL_PHASES_OF_CONSTR: 117,
        NOT_CONSTRUCTION_RELATED: 17,
        POST_CONSTRUCTION_PHASE: 83,
        PRIOR_TO_CONSTRUCTION_PHASE: 223,
        UNSPECIFIED: 8,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 47,
    name: {
      en: 'Thompson--Okanagan',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 10,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 3,
        ENFORCEMENT: 5,
        ENVIRONMENTAL_PROTECTION: 40,
        FINANCIAL: 6,
        INTEGRITY_MANAGEMENT: 30,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 3,
        SECURITY: 2,
        SOCIO_ECONOMIC: 12,
        STANDARD_CONDITION: 40,
        SUNSET_CLAUSE: 8,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 74,
        IN_PROGRESS: 62,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 94,
        STANDARD: 42,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 44,
        REQUIRED: 92,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 9,
        EXPIRY_DATE_OF_REG_INSTR: 9,
        INCLUDES_ALL_PHASES_OF_CONSTR: 43,
        NOT_CONSTRUCTION_RELATED: 17,
        POST_CONSTRUCTION_PHASE: 21,
        PRIOR_TO_CONSTRUCTION_PHASE: 36,
        UNSPECIFIED: 1,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 48,
    name: {
      en: 'Kootenay',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 1,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 2,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 4,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 9,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 5,
        STANDARD: 4,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 4,
        REQUIRED: 5,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 4,
        POST_CONSTRUCTION_PHASE: 1,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 49,
    name: {
      en: 'Parklands',
      __typename: 'TranslatedStringType',
    },
    province: 'MB',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 4,
        FINANCIAL: 0,
        INTEGRITY_MANAGEMENT: 2,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 8,
        SUNSET_CLAUSE: 3,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 15,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 7,
        STANDARD: 8,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 10,
        REQUIRED: 5,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 3,
        INCLUDES_ALL_PHASES_OF_CONSTR: 6,
        NOT_CONSTRUCTION_RELATED: 0,
        POST_CONSTRUCTION_PHASE: 2,
        PRIOR_TO_CONSTRUCTION_PHASE: 3,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 50,
    name: {
      en: 'Lower Mainland--Southwest',
      __typename: 'TranslatedStringType',
    },
    province: 'BC',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 42,
        DAMAGE_PREVENTION: 2,
        EMERGENCY_MANAGEMENT: 39,
        ENFORCEMENT: 5,
        ENVIRONMENTAL_PROTECTION: 203,
        FINANCIAL: 11,
        INTEGRITY_MANAGEMENT: 105,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 10,
        SECURITY: 7,
        SOCIO_ECONOMIC: 75,
        STANDARD_CONDITION: 60,
        SUNSET_CLAUSE: 14,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 233,
        IN_PROGRESS: 296,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 471,
        STANDARD: 58,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 72,
        REQUIRED: 457,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 75,
        EXPIRY_DATE_OF_REG_INSTR: 14,
        INCLUDES_ALL_PHASES_OF_CONSTR: 114,
        NOT_CONSTRUCTION_RELATED: 17,
        POST_CONSTRUCTION_PHASE: 83,
        PRIOR_TO_CONSTRUCTION_PHASE: 225,
        UNSPECIFIED: 1,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 51,
    name: {
      en: 'North Shore',
      __typename: 'TranslatedStringType',
    },
    province: 'NS',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 3,
        DAMAGE_PREVENTION: 5,
        EMERGENCY_MANAGEMENT: 1,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 5,
        FINANCIAL: 3,
        INTEGRITY_MANAGEMENT: 8,
        MANAGEMENT_SYSTEM: 9,
        SAFETY_MANAGEMENT: 2,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 9,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 25,
        IN_PROGRESS: 12,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 28,
        STANDARD: 9,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 18,
        REQUIRED: 19,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 5,
        NOT_CONSTRUCTION_RELATED: 5,
        POST_CONSTRUCTION_PHASE: 23,
        PRIOR_TO_CONSTRUCTION_PHASE: 2,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 52,
    name: {
      en: 'Kitchener--Waterloo--Barrie',
      __typename: 'TranslatedStringType',
    },
    province: 'ON',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 2,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 1,
        ENVIRONMENTAL_PROTECTION: 9,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 10,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 5,
        STANDARD_CONDITION: 8,
        SUNSET_CLAUSE: 2,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 33,
        IN_PROGRESS: 1,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 26,
        STANDARD: 8,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 8,
        REQUIRED: 26,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 1,
        EXPIRY_DATE_OF_REG_INSTR: 2,
        INCLUDES_ALL_PHASES_OF_CONSTR: 6,
        NOT_CONSTRUCTION_RELATED: 4,
        POST_CONSTRUCTION_PHASE: 10,
        PRIOR_TO_CONSTRUCTION_PHASE: 10,
        UNSPECIFIED: 1,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
  {
    id: 53,
    name: {
      en: 'Yukon',
      __typename: 'TranslatedStringType',
    },
    province: 'YT',
    aggregatedCount: {
      theme: {
        ADMINISTRATIVE: 1,
        DAMAGE_PREVENTION: 0,
        EMERGENCY_MANAGEMENT: 0,
        ENFORCEMENT: 0,
        ENVIRONMENTAL_PROTECTION: 1,
        FINANCIAL: 2,
        INTEGRITY_MANAGEMENT: 1,
        MANAGEMENT_SYSTEM: 0,
        SAFETY_MANAGEMENT: 0,
        SECURITY: 0,
        SOCIO_ECONOMIC: 0,
        STANDARD_CONDITION: 4,
        SUNSET_CLAUSE: 1,
        __typename: 'AggregatedCountConditionTheme',
      },
      __typename: 'AggregatedCountType',
      status: {
        CLOSED: 8,
        IN_PROGRESS: 0,
        __typename: 'AggregatedCountConditionStatus',
      },
      type: {
        NON_STANDARD: 4,
        STANDARD: 4,
        __typename: 'AggregatedCountConditionType',
      },
      filing: {
        NOT_REQUIRED: 4,
        REQUIRED: 4,
        __typename: 'AggregatedCountConditionFiling',
      },
      phase: {
        ABANDONMENT: 0,
        DURING_CONSTRUCTION_PHASE: 0,
        EXPIRY_DATE_OF_REG_INSTR: 1,
        INCLUDES_ALL_PHASES_OF_CONSTR: 3,
        NOT_CONSTRUCTION_RELATED: 3,
        POST_CONSTRUCTION_PHASE: 1,
        PRIOR_TO_CONSTRUCTION_PHASE: 0,
        UNSPECIFIED: 0,
        __typename: 'AggregatedCountConditionPhase',
      },
    },
    __typename: 'RegionType',
  },
];

export default locationData;
