export default [
  {
    id: 1225,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 14,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 12 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 1 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 2 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 3 },
        { name: 'FINANCIAL', count: 0 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 1 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 2 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 6 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 1 },
        { name: 'CLOSED', count: 8 },
        { name: 'NO_FILING_REQUIRED', count: 2 },
        { name: 'AWAITING_FILING', count: 22 },
        { name: 'OVERDUE_FILING', count: 0 },
        { name: 'UNDER_REVIEW', count: 7 },
        { name: 'REVIEW_COMPLETE', count: 4 },
        { name: 'AWAITING_IR_RESPONSE', count: 8 },
        { name: 'READY_FOR_BOARD_DECISION', count: 3 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 12 },
        { name: 'AMENDED', count: 0 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 13 },
        { name: 'STANDARD', count: 31 },
      ],
      filing: [
        { name: 'REQUIRED', count: 0 },
        { name: 'NOT_REQUIRED', count: 7 },
      ],
    },
  },
  {
    id: 1226,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 102,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 3 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 6 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 11 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 3 },
        { name: 'EMERGENCY_MANAGEMENT', count: 7 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 4 },
        { name: 'FINANCIAL', count: 13 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 6 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 7 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 2 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 5 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 2 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 8 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 5 },
        { name: 'CLOSED', count: 3 },
        { name: 'NO_FILING_REQUIRED', count: 11 },
        { name: 'AWAITING_FILING', count: 10 },
        { name: 'OVERDUE_FILING', count: 12 },
        { name: 'UNDER_REVIEW', count: 9 },
        { name: 'REVIEW_COMPLETE', count: 4 },
        { name: 'AWAITING_IR_RESPONSE', count: 11 },
        { name: 'READY_FOR_BOARD_DECISION', count: 7 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 9 },
        { name: 'AMENDED', count: 0 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 15 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'REQUIRED', count: 3 },
        { name: 'NOT_REQUIRED', count: 5 },
      ],
    },
  },
  {
    id: 1227,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 19,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 12 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 1 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 2 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 4 },
        { name: 'DAMAGE_PREVENTION', count: 11 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 3 },
        { name: 'FINANCIAL', count: 5 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 14 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 7 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 15 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 26 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 3 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 8 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 14 },
        { name: 'CLOSED', count: 8 },
        { name: 'NO_FILING_REQUIRED', count: 12 },
        { name: 'AWAITING_FILING', count: 22 },
        { name: 'OVERDUE_FILING', count: 0 },
        { name: 'UNDER_REVIEW', count: 7 },
        { name: 'REVIEW_COMPLETE', count: 14 },
        { name: 'AWAITING_IR_RESPONSE', count: 8 },
        { name: 'READY_FOR_BOARD_DECISION', count: 3 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 12 },
        { name: 'AMENDED', count: 10 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 0 },
        { name: 'STANDARD', count: 3 },
      ],
      filing: [
        { name: 'REQUIRED', count: 10 },
        { name: 'NOT_REQUIRED', count: 7 },
      ],
    },
  },
  {
    id: 1228,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 12,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 12 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 1 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 2 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 0 },
        { name: 'EMERGENCY_MANAGEMENT', count: 2 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 3 },
        { name: 'FINANCIAL', count: 0 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 1 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 2 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 6 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 1 },
        { name: 'CLOSED', count: 8 },
        { name: 'NO_FILING_REQUIRED', count: 2 },
        { name: 'AWAITING_FILING', count: 22 },
        { name: 'OVERDUE_FILING', count: 0 },
        { name: 'UNDER_REVIEW', count: 7 },
        { name: 'REVIEW_COMPLETE', count: 4 },
        { name: 'AWAITING_IR_RESPONSE', count: 8 },
        { name: 'READY_FOR_BOARD_DECISION', count: 3 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 12 },
        { name: 'AMENDED', count: 0 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 13 },
        { name: 'STANDARD', count: 31 },
      ],
      filing: [
        { name: 'REQUIRED', count: 0 },
        { name: 'NOT_REQUIRED', count: 7 },
      ],
    },
  },
  {
    id: 1229,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 3,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 3 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 6 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 11 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 3 },
        { name: 'EMERGENCY_MANAGEMENT', count: 7 },
        { name: 'ENFORCEMENT', count: 5 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 4 },
        { name: 'FINANCIAL', count: 13 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 2 },
        { name: 'SAFETY_MANAGEMENT', count: 7 },
        { name: 'SECURITY', count: 6 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 0 },
        { name: 'SUNSET_CLAUSE', count: 7 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 2 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 7 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 5 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 2 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 8 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 5 },
        { name: 'CLOSED', count: 3 },
        { name: 'NO_FILING_REQUIRED', count: 11 },
        { name: 'AWAITING_FILING', count: 10 },
        { name: 'OVERDUE_FILING', count: 12 },
        { name: 'UNDER_REVIEW', count: 9 },
        { name: 'REVIEW_COMPLETE', count: 4 },
        { name: 'AWAITING_IR_RESPONSE', count: 11 },
        { name: 'READY_FOR_BOARD_DECISION', count: 7 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 9 },
        { name: 'AMENDED', count: 0 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 15 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'REQUIRED', count: 3 },
        { name: 'NOT_REQUIRED', count: 5 },
      ],
    },
  },
  {
    id: 1230,
    name: 'Trans-Alta Limited-44245',
    shortName: 'Trans-Alta',
    numberOfConditions: 104,
    aggregatedCount: {
      instrument: [
        { name: 'ROUTING', count: 12 },
        { name: 'CONSTRUCTION', count: 11 },
        { name: 'ABANDONMENT', count: 1 },
        { name: 'OPENING', count: 22 },
        { name: 'MISC', count: 2 },
        { name: 'SAFETY', count: 9 },
        { name: 'TARIFFS', count: 11 },
      ],
      theme: [
        { name: 'ADMINISTRATIVE', count: 10 },
        { name: 'DAMAGE_PREVENTION', count: 20 },
        { name: 'EMERGENCY_MANAGEMENT', count: 12 },
        { name: 'ENFORCEMENT', count: 15 },
        { name: 'ENVIRONMENTAL_PROTECTION', count: 32 },
        { name: 'FINANCIAL', count: 0 },
        { name: 'INTEGRITY_MANAGEMENT', count: 11 },
        { name: 'MANAGEMENT_SYSTEM', count: 12 },
        { name: 'SAFETY_MANAGEMENT', count: 17 },
        { name: 'SECURITY', count: 21 },
        { name: 'SOCIO_ECONOMIC', count: 11 },
        { name: 'STANDARD_CONDITION', count: 20 },
        { name: 'SUNSET_CLAUSE', count: 15 },
      ],
      phase: [
        { name: 'ABANDONMENT', count: 0 },
        { name: 'DURING_CONSTRUCTION_PHASE', count: 17 },
        { name: 'EXPIRY_DATE_OF_REG_INSTR', count: 16 },
        { name: 'INCLUDES_ALL_PHASES_OF_CONSTR', count: 12 },
        { name: 'NOT_CONSTRUCTION_RELATED', count: 33 },
        { name: 'POST_CONSTRUCTION_PHASE', count: 4 },
        { name: 'PRIOR_TO_THE_CONSTRUCTION_PHASE', count: 2 },
        { name: 'UNSPECIFIED', count: 5 },
      ],
      status: [
        { name: 'IN_PROGRESS', count: 1 },
        { name: 'CLOSED', count: 8 },
        { name: 'NO_FILING_REQUIRED', count: 2 },
        { name: 'AWAITING_FILING', count: 22 },
        { name: 'OVERDUE_FILING', count: 0 },
        { name: 'UNDER_REVIEW', count: 7 },
        { name: 'REVIEW_COMPLETE', count: 4 },
        { name: 'AWAITING_IR_RESPONSE', count: 8 },
        { name: 'READY_FOR_BOARD_DECISION', count: 3 },
        { name: 'FURTHER_INFORMATION_REQUIRED', count: 12 },
        { name: 'AMENDED', count: 0 },
        { name: 'SATISFACTORY', count: 7 },
      ],
      type: [
        { name: 'NON_STANDARD', count: 13 },
        { name: 'STANDARD', count: 0 },
      ],
      filing: [
        { name: 'REQUIRED', count: 0 },
        { name: 'NOT_REQUIRED', count: 7 },
      ],
    },
  },
];
