export default {
  counts: [
    {
      id: 1225,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 12,
          CONSTRUCTION: 11,
          ABANDONMENT: 1,
          OPENING: 22,
          MISC: 2,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 10,
          DAMAGE_PREVENTION: 0,
          EMERGENCY_MANAGEMENT: 2,
          ENFORCEMENT: 5,
          ENVIRONMENTAL_PROTECTION: 3,
          FINANCIAL: 0,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 2,
          SAFETY_MANAGEMENT: 7,
          SECURITY: 1,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 0,
          SUNSET_CLAUSE: 15,
        },
        phase: {
          ABANDONMENT: 2,
          DURING_CONSTRUCTION_PHASE: 7,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 6,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 12,
          NOT_CONSTRUCTION_RELATED: 33,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 2,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 1,
          CLOSED: 8,
          NO_FILING_REQUIRED: 2,
          AWAITING_FILING: 22,
          OVERDUE_FILING: 0,
          UNDER_REVIEW: 7,
          REVIEW_COMPLETE: 4,
          AWAITING_IR_RESPONSE: 8,
          READY_FOR_BOARD_DECISION: 3,
          FURTHER_INFORMATION_REQUIRED: 12,
          AMENDED: 0,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 13,
          STANDARD: 31,
        },
        filing: {
          REQUIRED: 0,
          NOT_REQUIRED: 7,
        },
      },
    },
    {
      id: 1226,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 3,
          CONSTRUCTION: 11,
          ABANDONMENT: 6,
          OPENING: 22,
          MISC: 11,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 10,
          DAMAGE_PREVENTION: 3,
          EMERGENCY_MANAGEMENT: 7,
          ENFORCEMENT: 5,
          ENVIRONMENTAL_PROTECTION: 4,
          FINANCIAL: 13,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 2,
          SAFETY_MANAGEMENT: 7,
          SECURITY: 6,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 0,
          SUNSET_CLAUSE: 7,
        },
        phase: {
          ABANDONMENT: 2,
          DURING_CONSTRUCTION_PHASE: 7,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 5,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 2,
          NOT_CONSTRUCTION_RELATED: 8,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 2,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 5,
          CLOSED: 3,
          NO_FILING_REQUIRED: 11,
          AWAITING_FILING: 10,
          OVERDUE_FILING: 12,
          UNDER_REVIEW: 9,
          REVIEW_COMPLETE: 4,
          AWAITING_IR_RESPONSE: 11,
          READY_FOR_BOARD_DECISION: 7,
          FURTHER_INFORMATION_REQUIRED: 9,
          AMENDED: 0,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 15,
          STANDARD: 0,
        },
        filing: {
          REQUIRED: 3,
          NOT_REQUIRED: 5,
        },
      },
    },
    {
      id: 1227,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 12,
          CONSTRUCTION: 11,
          ABANDONMENT: 1,
          OPENING: 22,
          MISC: 2,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 4,
          DAMAGE_PREVENTION: 11,
          EMERGENCY_MANAGEMENT: 2,
          ENFORCEMENT: 5,
          ENVIRONMENTAL_PROTECTION: 3,
          FINANCIAL: 5,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 14,
          SAFETY_MANAGEMENT: 7,
          SECURITY: 7,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 0,
          SUNSET_CLAUSE: 15,
        },
        phase: {
          ABANDONMENT: 15,
          DURING_CONSTRUCTION_PHASE: 7,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 26,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 12,
          NOT_CONSTRUCTION_RELATED: 3,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 8,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 14,
          CLOSED: 8,
          NO_FILING_REQUIRED: 12,
          AWAITING_FILING: 22,
          OVERDUE_FILING: 0,
          UNDER_REVIEW: 7,
          REVIEW_COMPLETE: 14,
          AWAITING_IR_RESPONSE: 8,
          READY_FOR_BOARD_DECISION: 3,
          FURTHER_INFORMATION_REQUIRED: 12,
          AMENDED: 10,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 0,
          STANDARD: 3,
        },
        filing: {
          REQUIRED: 10,
          NOT_REQUIRED: 7,
        },
      },
    },
    {
      id: 1228,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 12,
          CONSTRUCTION: 11,
          ABANDONMENT: 1,
          OPENING: 22,
          MISC: 2,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 10,
          DAMAGE_PREVENTION: 0,
          EMERGENCY_MANAGEMENT: 2,
          ENFORCEMENT: 5,
          ENVIRONMENTAL_PROTECTION: 3,
          FINANCIAL: 0,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 2,
          SAFETY_MANAGEMENT: 7,
          SECURITY: 1,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 0,
          SUNSET_CLAUSE: 15,
        },
        phase: {
          ABANDONMENT: 2,
          DURING_CONSTRUCTION_PHASE: 7,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 6,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 12,
          NOT_CONSTRUCTION_RELATED: 33,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 2,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 1,
          CLOSED: 8,
          NO_FILING_REQUIRED: 2,
          AWAITING_FILING: 22,
          OVERDUE_FILING: 0,
          UNDER_REVIEW: 7,
          REVIEW_COMPLETE: 4,
          AWAITING_IR_RESPONSE: 8,
          READY_FOR_BOARD_DECISION: 3,
          FURTHER_INFORMATION_REQUIRED: 12,
          AMENDED: 0,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 13,
          STANDARD: 31,
        },
        filing: {
          REQUIRED: 0,
          NOT_REQUIRED: 7,
        },
      },
    },
    {
      id: 1229,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 3,
          CONSTRUCTION: 11,
          ABANDONMENT: 6,
          OPENING: 22,
          MISC: 11,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 10,
          DAMAGE_PREVENTION: 3,
          EMERGENCY_MANAGEMENT: 7,
          ENFORCEMENT: 5,
          ENVIRONMENTAL_PROTECTION: 4,
          FINANCIAL: 13,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 2,
          SAFETY_MANAGEMENT: 7,
          SECURITY: 6,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 0,
          SUNSET_CLAUSE: 7,
        },
        phase: {
          ABANDONMENT: 2,
          DURING_CONSTRUCTION_PHASE: 7,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 5,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 2,
          NOT_CONSTRUCTION_RELATED: 8,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 2,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 5,
          CLOSED: 3,
          NO_FILING_REQUIRED: 11,
          AWAITING_FILING: 10,
          OVERDUE_FILING: 12,
          UNDER_REVIEW: 9,
          REVIEW_COMPLETE: 4,
          AWAITING_IR_RESPONSE: 11,
          READY_FOR_BOARD_DECISION: 7,
          FURTHER_INFORMATION_REQUIRED: 9,
          AMENDED: 0,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 15,
          STANDARD: 0,
        },
        filing: {
          REQUIRED: 3,
          NOT_REQUIRED: 5,
        },
      },
    },
    {
      id: 1230,
      name: {
        en: 'Trans-Alta Limited-44245',
        fr: 'nameInFrench',
      },
      shortName: {
        en: 'Trans-Alta',
        fr: 'nameInFrench',
      },
      data: {
        instrument: {
          ROUTING: 12,
          CONSTRUCTION: 11,
          ABANDONMENT: 1,
          OPENING: 22,
          MISC: 2,
          SAFETY: 9,
          TARIFFS: 11,
        },
        theme: {
          ADMINISTRATIVE: 10,
          DAMAGE_PREVENTION: 20,
          EMERGENCY_MANAGEMENT: 12,
          ENFORCEMENT: 15,
          ENVIRONMENTAL_PROTECTION: 32,
          FINANCIAL: 0,
          INTEGRITY_MANAGEMENT: 11,
          MANAGEMENT_SYSTEM: 12,
          SAFETY_MANAGEMENT: 17,
          SECURITY: 21,
          SOCIO_ECONOMIC: 11,
          STANDARD_CONDITION: 20,
          SUNSET_CLAUSE: 15,
        },
        phase: {
          ABANDONMENT: 0,
          DURING_CONSTRUCTION_PHASE: 17,
          EXPIRY_DATE_OF_REGULATORY_INSTRUMENT: 16,
          INCLUDES_ALL_PHASES_OF_CONSTRUCTION: 12,
          NOT_CONSTRUCTION_RELATED: 33,
          POST_CONSTRUCTION_PHASE: 4,
          PRIOR_TO_CONSTRUCTION_PHASE: 2,
          UNSPECIFIED: 5,
        },
        status: {
          IN_PROGRESS: 1,
          CLOSED: 8,
          NO_FILING_REQUIRED: 2,
          AWAITING_FILING: 22,
          OVERDUE_FILING: 0,
          UNDER_REVIEW: 7,
          REVIEW_COMPLETE: 4,
          AWAITING_IR_RESPONSE: 8,
          READY_FOR_BOARD_DECISION: 3,
          FURTHER_INFORMATION_REQUIRED: 12,
          AMENDED: 0,
          SATISFACTORY: 7,
        },
        type: {
          NON_STANDARD: 13,
          STANDARD: 0,
        },
        filing: {
          REQUIRED: 0,
          NOT_REQUIRED: 7,
        },
      },
    },
  ],
};
