import React from 'react';
import withInteraction, { getInteractionProps } from 'storybook-addon-interaction';
import { storiesForComponent } from '../../../.storybook/utils';
import withStatus from '../../../.storybook/addon-status';
import ConditionExplorer from './';
import ReadMe from './README.md';

const keywords = [
  'Environment',
  'fisheries',
  'groundwater monitoring',
  'groundwater',
  'water quality',
  'Environmental Impact assessment',
  'seasonal rare plant survey',
  'Detroit River',
  'agricultural soils',
  'Culturally modified trees',
  'breeding bird survey',
  'Athabasca River',
  'Beaver Creek',
  'soil',
  'drinking water',
  'Kyklo Creek',
  'Kobes Creek',
  'environment alignment',
  'environmental protection',
  'environmental communication and training plan',
  'rare plant survey',
  'Horn River',
  'noxious weeds',
  'fugitive emission',
  'wetlands',
  'environmental issues',
  'environment',
  'Boundary Lake',
  'vegetation',
  'water',
  'marine spill',
  'habitat',
  'waste',
  'Aitken Creek',
  'wildlife',
  'Assiniboine River',
  'protection of the environment',
  'watercourse crossing',
  'protection plan',
  'soils',
  'erosion control measures',
  'spill',
  'Beatton River',
  'Burnt Cabin Creek',
  'Cactus Lake',
  'Kitimat River',
  'Chinchaga River',
  'environmental assessment',
  'department of fisheries and oceans',
  'air',
  'emissions',
  'Christina River',
  'Clore River',
  'McLeod River',
  'Moody Creek',
  'Pesh Creek',
  'Paddle River',
  'Lichen Creek',
  'Leach Creek',
  'Nosehill Creek',
  'Metlahdoa Creek',
  'Frenchman River',
  'Battle River',
  'Grand River',
  'horizontal directional drill',
  'House River',
  'Kitimat Terminal',
  'Little Hay River',
  'Piapot Creek',
  'Red Deer River',
  'Salish Sea',
  'South Saskatchewan River',
  'Stewart Creek',
  'Werniuk Creek',
  'Westridge Marine Terminal',
];

storiesForComponent('Components|ConditionExplorer', module, ReadMe)
  .addDecorator(withStatus('functionalityUnderDevelopment'))
  .addDecorator(withInteraction({ actions: ['changeVisibleWords'] }))
  .add('default', () => (
    <ConditionExplorer keywords={keywords} {...getInteractionProps()} />
  ));
